(Enhancement) Ginkgo test framework for k8tls
kubearmor/k8tls pull request #18
Opened 2023-08-14 16:37 UTC by PrimalPimmy

Added test framework using ginkgo, current has two cases but as more features are added, more tests can be put here.

2023-08-17 06:20 UTC, nyrahul requested changes
Looks mostly good to me. Please check the comments. Thanks

2023-08-19 16:20 UTC, nyrahul requested changes

2023-08-19 16:20 UTC, nyrahul commented on .github/workflows/ci-test-ginkgo.yml
> +        run: kubectl apply -f ./tests/res/wordpress-mysql-dep.yaml
Need to add wait to check if the pods are up and running.

2023-08-19 16:20 UTC, nyrahul commented on .github/workflows/scripts/install_k3s.sh
> +kubectl get pods -A
```suggestion
curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--disable=traefik" sh -
[[ $? != 0 ]] && echo "Failed to install k3s" && exit 1

mkdir -p ~/.kube && cp /etc/rancher/k3s/k3s.yaml ~/.kube/config

kubectl wait --for=condition=ready --timeout=15m -n kube-system pod -l k8s-app=metrics-server
```

2023-08-19 16:20 UTC, nyrahul commented on tests/k8tls-test.go
> +
```suggestion
```

2023-08-19 16:20 UTC, nyrahul commented on tests/k8tls-test.go
> +func matchCSV(file1 string, file2 string) {
This function is clumsy and huge scope for improvisation. Secondly, it is not a generic matchCSV operation. There are fields `address` hardcoded in this API.

2023-08-19 16:29 UTC, PrimalPimmy commented on tests/k8tls-test.go
> +func matchCSV(file1 string, file2 string) {
What do you mean by clumsy? Also yes I was wondering how I would test something like Address which keeps on changing.

Was thinking of using regex based matching in the Address column, matching address:port formats . No other ideas yet, thoughts?

2023-08-29 10:40 UTC, nyrahul approved these changes

2023-08-29 10:40 UTC, merged