feat: Add Support to find Exposed ports in AWS EKS
kubearmor/k8tls pull request #47
Opened 2024-12-13 17:11 UTC by anurag-rajawat

2024-12-15 14:29 UTC, daemon1024 requested changes

2024-12-15 14:29 UTC, daemon1024 commented on k8s/job.yaml
> +            runAsUser: 0
This is fine for the demo, but we need to avoid this and fix the permission issue

2024-12-15 14:29 UTC, daemon1024 commented on src/findings_tls
> +		clusterName=$(curl -s http://169.254.169.254/latest/user-data | grep -E '^/etc/eks/bootstrap\.sh\s+([^\s]+)' | cut -d' ' -f2 2> /dev/null)
We need to keep the IP configurable from env variable and default to this IP

2024-12-15 14:42 UTC, anurag-rajawat commented on src/findings_tls
> +		clusterName=$(curl -s http://169.254.169.254/latest/user-data | grep -E '^/etc/eks/bootstrap\.sh\s+([^\s]+)' | cut -d' ' -f2 2> /dev/null)
> We need to keep the IP configurable from env variable and default to this IP

The IP for AWS, GCP and Azure is the same, although the endpoints are different, so I don't think we need to make this IP configurable.

This is AWS specific and we will handle other providers later.

2024-12-16 02:57 UTC, nyrahul approved these changes

2024-12-16 02:58 UTC, merged